version: "3"
services:
  db:
    image: postgres
    ports:
      - 55555:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgrespass
    volumes:
      - kabu_db:/var/lib/postgresql/data
  redis:
    image: redis
    ports:
      - "6379:6379"
    command: redis-server
    volumes:
      - redis-data:/data

volumes:
  kabu_db:
  redis-data:
