version: "3"
services:
  db:
    image: postgres
    ports:
      - 54321:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgrespass
    volumes:
      - kabu_db:/var/lib/postgresql/data

volumes:
  kabu_db:
