export const T = {
  LOAD_BRAND_LATEST_DIVIDEND: 'LOAD_BRAND_LATEST_DIVIDEND',
  GET_DIVIDEND_TREND: 'GET_DIVIDEND_TREND',
  SORT_BRAND_LATEST_DIVIIEDEND: 'SORT_BRAND_LATEST_DIVIIEDEND',
  CLOSE_DIVIDEND_TREND: 'CLOSE_DIVIDEND_TREND',
  CLICK_PAGENATE: 'CLICK_PAGENATE',
  CLICK_PREV_PAGENATE: 'CLICK_PREV_PAGENATE',
  CLICK_NEXT_PAGENATE: 'CLICK_NEXT_PAGENATE',
  CLICK_FIRST_PAGE: 'CLICK_FIRST_PAGE',
  CLICK_LAST_PAGE: 'CLICK_LAST_PAGE'
}